- name: enable common dirs
  file: name={{ item }} state=directory
  with_items:
  - "{{ CA_DIR }}"
  - /root/.kube
  - /etc/docker

- name: distribute cfssl tools
  copy: src={{ BASE_DIR }}/bin/{{ item }} dest={{ BIN_DIR }}/{{ item }} mode=0755
  with_items:
  - cfssl
  - cfssl-certinfo
  - cfssljson

- name: distribute CA certs
  copy: src={{ item }} dest={{ CA_DIR }}/{{ item }} mode=0644
  with_items:
  - ca.pem
  - ca-key.pem
  - ca.csr
  - ca-config.json

- name: disable firewall service
  when: ansible_distribution == "CentOS"
  yum: name={{ item }} state=absent
  with_items:
  - firewalld
  - firewalld-filesystem
  - python-firewall

- name: disable selinux service
  shell: "setenforce 0 && echo SELINUX=disabled > /etc/selinux/config"
  when: ansible_distribution == "CentOS"
  ignore_errors: true

- name: load br_netfilter module
  modprobe: name=br_netfilter state=present

- name: distribute sysctl configuration
  copy: src=k8s-sysctl.conf dest=/etc/sysctl.d/k8s-sysctl.conf

- name: enable sysctl configuration
  shell: "sysctl -p /etc/sysctl.d/k8s-sysctl.conf"
  ignore_errors: true
